const states: { id: string; label: string }[] = [
  { id: "AC", label: "AC" },
  { id: "AL", label: "AL" },
  { id: "AP", label: "AP" },
  { id: "AM", label: "AM" },
  { id: "BA", label: "BA" },
  { id: "CE", label: "CE" },
  { id: "DF", label: "DF" },
  { id: "ES", label: "ES" },
  { id: "GO", label: "GO" },
  { id: "MA", label: "MA" },
  { id: "MT", label: "MT" },
  { id: "MS", label: "MS" },
  { id: "MG", label: "MG" },
  { id: "PA", label: "PA" },
  { id: "PB", label: "PB" },
  { id: "PR", label: "PR" },
  { id: "PE", label: "PE" },
  { id: "PI", label: "PI" },
  { id: "RJ", label: "RJ" },
  { id: "RN", label: "RN" },
  { id: "RS", label: "RS" },
  { id: "RO", label: "RO" },
  { id: "RR", label: "RR" },
  { id: "SC", label: "SC" },
  { id: "SP", label: "SP" },
  { id: "SE", label: "SE" },
  { id: "TO", label: "TO" },
];

export default states;
